/**
 * AUTO-GENERATED by groundx-design-standards/scripts/generate-mirrors.mjs
 * Source of truth: groundx-design-standards/tokens.json
 *
 * DO NOT EDIT THIS FILE BY HAND. Re-run the generator instead:
 *   cd groundx-design-standards && node scripts/generate-mirrors.mjs
 *
 * Hand-written chrome tokens (drawerWidth, NAV_ICON_GREY, etc.) and legacy
 * alias re-exports live in constants.chrome.ts and constants.legacy.ts.
 * The barrel constants.ts re-exports all three.
 */

// ────────────────────────────────────────────────────────────────────────
// Colors — brand palette
// ────────────────────────────────────────────────────────────────────────

/** Primary dark. Headings, links, dark surfaces, strong borders. Not true black. */
export const NAVY = "#29335c";
/** Primary CTA + accent. Submit buttons, success chips, eyebrows on navy. */
export const GREEN = "#a1ec83";
/** Secondary accent. Icon-button bg, tag bg, cyan card fill. */
export const CYAN = "#c1e8ee";
/** Quiet section bg. Pale cyan wash, callouts, tint cards. */
export const TINT = "#eff9fb";
/** Label / highlight accent. Section eyebrows, pull-quote highlights. NOT the primary CTA. */
export const CORAL = "#f3663f";
/** Default body color. Slightly-warmer navy. */
export const BODY_TEXT = "#40496b";
/** Alt section bg, input field fill. */
export const GRAY = "#f2f4f5";
/** Surface fill. Cards, inputs, table cells, modal panels. */
export const WHITE = "#ffffff";
/** Default hairline. Navy at 10%. */
export const BORDER = "rgba(41, 51, 92, 0.1)";

// ────────────────────────────────────────────────────────────────────────
// Colors — support palette
// ────────────────────────────────────────────────────────────────────────

/** Destructive / failure. */
export const ERROR_RED = "#f70d1a";
/** Soft warning. */
export const LIGHTER_RED = "#ff7f7f";
/** Inline link accent. Rare. */
export const BLUE = "#0b99ff";
/** Inactive chrome. Slide numbers, timestamps. */
export const DARK_GREY = "#81879a";

// ────────────────────────────────────────────────────────────────────────
// Typography — family & features
// ────────────────────────────────────────────────────────────────────────

/** Served from Google Fonts; no self-hosting. */
export const FONT_FAMILY = "\"Inter\", system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif";
/** Single-story a (ss01), straight-leg R (cv11), tailed l (cv01). Applied on body. */
export const FONT_FEATURE_SETTINGS = "\"ss01\", \"cv11\", \"cv01\"";

// ────────────────────────────────────────────────────────────────────────
// Typography — weight ladder
// ────────────────────────────────────────────────────────────────────────

/** Body copy, subheads, most UI text. */
export const FONT_WEIGHT_BODY = 400;
/** Labels, eyebrows, CTAs, table headers. */
export const FONT_WEIGHT_LABEL = 600;
/** Headlines, emphasized inline words. */
export const FONT_WEIGHT_HEADLINE = 700;
/** Cover-slide headlines, display-stat numerals. */
export const FONT_WEIGHT_DISPLAY = 800;

// ────────────────────────────────────────────────────────────────────────
// Typography — letter spacing
// ────────────────────────────────────────────────────────────────────────

/** Uppercase eyebrows and overline labels. */
export const LETTER_SPACING_LABEL = "0.12em";
/** Button labels (tighter than eyebrows). */
export const LETTER_SPACING_BUTTON = "0.04em";
/** Legacy chrome — MuiChip, GxPill, button-internal labels. */
export const LETTER_SPACING_CHIP = "0.5px";
/** Display-heading optical tracking (negative). */
export const LETTER_SPACING_DISPLAY_TIGHT = "-0.01em";
/** Page-heading optical tracking. */
export const LETTER_SPACING_HEADING_TIGHT = "-0.005em";

// ────────────────────────────────────────────────────────────────────────
// Typography — line height
// ────────────────────────────────────────────────────────────────────────

/** Cover / display. */
export const LINE_HEIGHT_DISPLAY = 1.1;
/** Page heading. */
export const LINE_HEIGHT_HEADING = 1.15;
/** Section heading. */
export const LINE_HEIGHT_SECTION = 1.2;
/** Subsection. */
export const LINE_HEIGHT_SUBSECTION = 1.25;
/** Card heading. */
export const LINE_HEIGHT_CARD_HEADING = 1.3;
/** Card subhead. */
export const LINE_HEIGHT_CARD_SUBHEAD = 1.4;
/** Body-sm / caption. */
export const LINE_HEIGHT_TIGHT_BODY = 1.5;
/** Default body (web is looser than slides). */
export const LINE_HEIGHT_BODY = 1.6;

// ────────────────────────────────────────────────────────────────────────
// Web size scale
// ────────────────────────────────────────────────────────────────────────

/** Display heading (hero, cover). Weight 700. (40px) */
export const FONT_SIZE_H1 = "2.5rem";
/** Page heading. Weight 700. (32px) */
export const FONT_SIZE_H2 = "2rem";
/** Section heading. Weight 700. (26px) */
export const FONT_SIZE_H3 = "1.625rem";
/** Subsection. Weight 700. (22px) */
export const FONT_SIZE_H4 = "1.375rem";
/** Card heading. Weight 700. (18px) */
export const FONT_SIZE_H5 = "1.125rem";
/** Card subhead. Weight 700. (16px) */
export const FONT_SIZE_H6 = "1rem";
/** Default body. Weight 400. (16px) */
export const FONT_SIZE_BODY = "1rem";
/** Secondary paragraphs, table rows. (14px) */
export const FONT_SIZE_BODY_SM = "0.875rem";
/** Metadata / timestamps / captions. (13px) */
export const FONT_SIZE_CAPTION = "0.8125rem";
/** Uppercase eyebrows, overline labels. (12px) */
export const FONT_SIZE_LABEL = "0.75rem";
/** Dense inline pill chrome (GxPill dense mode). (11px) */
export const FONT_SIZE_LABEL_DENSE = "0.7rem";

// ────────────────────────────────────────────────────────────────────────
// Border radii (webflow scale)
// ────────────────────────────────────────────────────────────────────────

/** Tight inner shapes — hairline divider wraps, inline chips. */
export const BORDER_RADIUS_SM = "4px";
/** Inner / nested surfaces, inputs, code blocks. */
export const BORDER_RADIUS = "6px";
/** Dropdown menus, toast, medium-surface containers. */
export const BORDER_RADIUS_2X = "12px";
/** Top-level cards, accordions. Default unless a reason not to. */
export const BORDER_RADIUS_CARD = "20px";
/** Buttons, pills, tags, segmented button ends. */
export const BORDER_RADIUS_PILL = "200px";

// ────────────────────────────────────────────────────────────────────────
// Spacing (MUI units, 1 = 8px)
// ────────────────────────────────────────────────────────────────────────

/** Default inner padding on GxCard and most surfaces. 16px. */
export const PADDING = 2;
/** Outer padding on the main content pane (desktop). 40px. */
export const MAIN_CONTENT_PADDING = 5;
/** Top margin on main content to clear the fixed AppBar. 56px. */
export const MAIN_CONTENT_TOP_MARGIN = 7;

// ────────────────────────────────────────────────────────────────────────
// Durations
// ────────────────────────────────────────────────────────────────────────

/** Auto-dismiss ms for toast / message bar. */
export const MESSAGE_BAR_DURATION = 20000;
